# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f82b8a3583267e9fb01510f6ab269cd65d67a24d62cd81c5a9726259f96c724c979771272d363a44836c0ea9304f42fb5538d6d19181d27479ec20e62258be

test:
  secret_key_base: 065ad574aae7023e5231ec8d63cca3c3adde52364f9ba2b5aff7dc02caebec2f0313038f535f772582ecf8c5a8de7b7cb17f288ff7c0fcdd54708906d96ef011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
